// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrJQhvQSlqTvYctNyjPoYKRc60IjXAS_I',
    appId: '1:781554751244:web:a653da44bf5c87dbe79b29',
    messagingSenderId: '781554751244',
    projectId: 'living-smile-app',
    authDomain: 'living-smile-app.firebaseapp.com',
    storageBucket: 'living-smile-app.firebasestorage.app',
    measurementId: 'G-H947DHQ49Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD8LTOnhH1x_7Ed6ZXLDEBvuHOLwFwSgY',
    appId: '1:781554751244:android:439e209e806f4282e79b29',
    messagingSenderId: '781554751244',
    projectId: 'living-smile-app',
    storageBucket: 'living-smile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFJqh23lmHPQ399NZVbkRxySNba6c3Ssk',
    appId: '1:781554751244:ios:3143a741540d998ee79b29',
    messagingSenderId: '781554751244',
    projectId: 'living-smile-app',
    storageBucket: 'living-smile-app.firebasestorage.app',
    iosBundleId: 'tz.or.lsi.livingSmileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFJqh23lmHPQ399NZVbkRxySNba6c3Ssk',
    appId: '1:781554751244:ios:3143a741540d998ee79b29',
    messagingSenderId: '781554751244',
    projectId: 'living-smile-app',
    storageBucket: 'living-smile-app.firebasestorage.app',
    iosBundleId: 'tz.or.lsi.livingSmileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrJQhvQSlqTvYctNyjPoYKRc60IjXAS_I',
    appId: '1:781554751244:web:e36c0a6c01a3d077e79b29',
    messagingSenderId: '781554751244',
    projectId: 'living-smile-app',
    authDomain: 'living-smile-app.firebaseapp.com',
    storageBucket: 'living-smile-app.firebasestorage.app',
    measurementId: 'G-W9PP04HNZ3',
  );
}
